### ISSUE TITLE
[1장] 첫 예제 length와 head의 concat 순서

### ISSUE THREAD

**Issue by not-for-me** [jooyunghan/programming-look-and-say-src#1]
안녕하세요 주영님,
책 사놓고 이제 첫 장을 따라하다가 첫 예제에서 뭔가 궁금한 것이 생겨서 질문드립니다. 
코드보면 아래와 같이 결과에 lenght를 먼저 concat하고 다음에 head를 붙이는데요

```
result += length;
result += head;
```

원래 lookAndSay에 따라  head를 먼저 concat하고 length하는게 아닌가 하여 이슈 등록합니다 :)

**Comment by jooyunghan** [comment]
와우 1번 이슈 감사합니다. 💯 

1장 앞에서 개미 수열 혹은 읽고 말하기 수열을 소개하면서 영어식 표현과 우리말 표현 두 가지 모두 가능하지만 책에서는 영어식 (길이 먼저)을 다룬다고 하였습니다. :-)

이 두 가지는 다행히 그냥 각 줄을 reverse 한 것이나 마찬가지라서 문제나 풀이를 크게 바꾸지 않더라구요.
